[package]
name = "oiio"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR BSD-3-Clause"
authors = ["Moritz Moeller <virtualritz@protonmail.com>", "Anders Langlands"]

[build-dependencies]
bbl-build = { git = "https://github.com/anderslanglands/bbl-build-rs.git" }

[dependencies]
anyhow = "1"
camino = "1.1"
num_enum = "0.7"
once_cell = { version = "1", features = ["parking_lot"] }
